name: gridmet_bmi
channels:
  - conda-forge
dependencies:
  - bmipy
  - click
  - numpy
  - pyyaml
  - requests
  - netcdf4
  - xarray
  - geopandas
  - matplotlib
  - rasterio
  - pytest
  - coverage
  - bmi-tester
