name: Test

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-test:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: gridmet_bmi
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}

      - name: Show conda installation info
        run: |
          conda info
          conda list

      - name: Build and install package
        run: |
          make install

      - name: Run unit tests
        run: |
          pytest

      - name: Test BMI
        if: ${{ matrix.python-version == '3.12' }}
        run: |
          make test-bmi

      - name: Run examples
        working-directory: ${{ github.workspace }}/examples
        run: |
          python debug.py
