name: Test

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install nox
        run: |
          pip install nox

      - name: Run unit tests (gridmet only, not BMI)
        run: |
          nox -s test -- tests/test_gridmet.py --python ${{ matrix.python-version }}

      - name: Test BMI
        if: ${{ matrix.python-version == '3.14' }}
        run: |
          nox -s test-bmi --python ${{ matrix.python-version }}

      - name: Run examples
        working-directory: ${{ github.workspace }}/examples
        if: ${{ matrix.python-version == '3.14' }}
        run: |
          pip install -e ..
          python debug.py
